### ISSUE TITLE
Hinweis wegen Verwechslungsgefahr

### ISSUE THREAD

**Issue by hpop** [arnef/kickertool#27]
Moin Arne,

da wir immer mal wieder Anfragen bekommen, ob wir dieses Repo noch pflegen, wollte ich mal fragen, ob du einen Hinweis einbinden könntest, der darauf hinweist, dass dieses Repo nicht mit unserem Kickertool (https://kickertool.de) zusammenhängt.

Beste Grüße

**Comment by meganoob1337** [comment]
@hpop wie würdest du dir den Hinweis vorstellen?
Liebe grüße,
Andrei :D

**Comment by meganoob1337** [comment]
@hpop guck mal in die Readme, passt das so für dich?
